name: ci

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v3

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node14-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.x
          run_install: |
            - args: [--reporter=silent]

      - name: Lint
        run: pnpm lint

