name: examples

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node14-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.x
          run_install: |
            - args: [--reporter=silent]

      - name: Build
        run: pnpm build

      - name: pnpm
        working-directory: ./examples/pnpm
        run: |
          pnpm i
          pnpm prisma-dl --help
          pnpm prisma-dl --engine query
          pnpm prisma generate
          pnpm prisma-dl --engine fmt
          pnpm prisma format

  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yarn
        working-directory: ./examples/yarn
        run: |
          yarn
          yarn prisma-dl --help
          yarn prisma-dl --engine query
          yarn prisma generate
          yarn prisma-dl --engine fmt
          yarn prisma format
